<?php
return array(
    array(
        'title' => '后台首页',
        'url' => U('Index/index'),
        'terms' => ((CONTROLLER_NAME == 'Index') and (in_array(ACTION_NAME, array('index')))),
        'icon' => 'th',
        'show' => isadmin('Index/index'),
        '_' => array(),
    ),
    array(
        'title' => '轮播大图',
        'url' => U('Banner/index'),
        'terms' => ((CONTROLLER_NAME == 'Banner') and (in_array(ACTION_NAME, array('index', 'add', 'edit')))),
        'icon' => 'user',
        'show' => isadmin('Banner/index'),
        '_' => array(),
    ),
    array(
        'title' => '新闻管理',
        'url' => U('News/index'),
        'terms' => '',
        'icon' => 'time',
        'show' => isadmin('News/index'),
        '_' => array(
            array(
                'title' => '信息列表',
                'url' => U('News/index'),
                'terms' => ((CONTROLLER_NAME == 'News') and (in_array(ACTION_NAME, array('index', 'add', 'edit')))),
                'icon' => '',
                'show' => isadmin('News/index'),
                '_' => array(),
            ),
            array(
                'title' => '类别管理',
                'url' => U('NewsCategory/index'),
                'terms' => ((CONTROLLER_NAME == 'NewsCategory') and (in_array(ACTION_NAME, array('index', 'add', 'edit')))),
                'icon' => '',
                'show' => isadmin('NewsCategory/index'),
                '_' => array(),
            ),
        ),
    ),
    array(
        'title' => '网站设置',
        'url' => U('Config/index'),
        'terms' => '',
        'icon' => 'wrench',
        'show' => isadmin('Config/index'),
        '_' => array(
            array(
                'title' => '基本配置',
                'url' => U('Config/index'),
                'terms' => ((CONTROLLER_NAME == 'Config') and (in_array(ACTION_NAME, array('index')))),
                'icon' => '',
                'show' => isadmin('Config/index'),
                '_' => array(),
            ),
            array(
                'title' => '其他配置',
                'url' => U('Config/other'),
                'terms' => ((CONTROLLER_NAME == 'Config') and (in_array(ACTION_NAME, array('other')))),
                'icon' => '',
                'show' => isadmin('Config/other'),
                '_' => array(),
            ),
        ),
    ),
    array(
        'title' => '用户留言',
        'url' => U('Feedback/index'),
        'terms' => ((CONTROLLER_NAME == 'Feedback') and (in_array(ACTION_NAME, array('index')))),
        'icon' => 'envelope',
        'show' => isadmin('Feedback/index'),
        '_' => array(),
    ),
    array(
        'title' => '单页栏目',
        'url' => U('About/index'),
        'terms' => ((CONTROLLER_NAME == 'About') and (in_array(ACTION_NAME, array('index', 'add', 'edit')))),
        'icon' => 'list-alt',
        'show' => isadmin('About/index'),
        '_' => array(),
    ),
    array(
        'title' => '单页面',
        'url' => U('Singlepage/edit', array('id' => 1)),
        'terms' => ((CONTROLLER_NAME == 'Singlepage') and (in_array(ACTION_NAME, array('edit'))) and (I('id') == 1)),
        'icon' => 'file-text-o',
        'show' => isadmin('Singlepage/edit'),
        '_' => array(),
    ),
    array(
        'title' => '管理员管理',
        'url' => U('Admin/index'),
        'terms' => '',
        'icon' => 'group',
        'show' => (in_array(session('admin_id'), array(1, 2))),
        '_' => array(
            array(
                'title' => '管理员列表',
                'url' => U('Admin/index'),
                'terms' => ((CONTROLLER_NAME == 'Admin') and (in_array(ACTION_NAME, array('index', 'add', 'edit')))),
                'icon' => '',
                'show' => (in_array(session('admin_id'), array(1, 2)) and C('POWER_ROUTE')),
                '_' => array(),
            ),
            array(
                'title' => '管理员组别',
                'url' => U('AdminGroup/index'),
                'terms' => ((CONTROLLER_NAME == 'AdminGroup') and (in_array(ACTION_NAME, array('index', 'add', 'edit')))),
                'icon' => '',
                'show' => (in_array(session('admin_id'), array(1, 2)) and C('POWER_ROUTE')),
                '_' => array(),
            ),
            array(
                'title' => '节点管理',
                'url' => U('AdminNode/index'),
                'terms' => ((CONTROLLER_NAME == 'AdminNode') and (in_array(ACTION_NAME, array('index', 'add', 'edit')))),
                'icon' => '',
                'show' => in_array(session('admin_id'), array(1)),
                '_' => array(),
            ),
        ),
    ),

);